import type { IVTableSheetOptions } from '@visactor/vtable-sheet'

export const DEFAULT_WORKBOOK_DATA: IVTableSheetOptions = {
  sheets: [
    {
      sheetKey: 'sheet-01',
      sheetTitle: 'Sheet1',
      columnCount: 26,
      rowCount: 1000,
      data: [],
      formulas: {},
      active: true,
      filter: true,
    },
  ],
  showFormulaBar: true,
  showSheetTab: true,
  defaultRowHeight: 25,
  defaultColWidth: 100,
  dragOrder: {
    enableDragColumnOrder: true,
    enableDragRowOrder: true,
  },
  undoRedo: { show: true },
}

export const BUDGET_TEMPLATE_DATA: IVTableSheetOptions = {
  sheets: [
    {
      sheetKey: 'budget-sheet',
      sheetTitle: 'Budget',
      columnCount: 4,
      rowCount: 100,
      data: [
        ['Monthly Budget', '', '', ''],
        ['', '', '', ''],
        ['Income', 'Amount', '', ''],
        ['Salary', 5000, '', ''],
        ['Freelance', 1000, '', ''],
        ['Other Income', 500, '', ''],
        ['Total Income', 6500, '', ''],
        ['', '', '', ''],
        ['Expenses', 'Amount', '', ''],
        ['Rent/Mortgage', 1500, '', ''],
        ['Utilities', 300, '', ''],
        ['Food & Groceries', 600, '', ''],
        ['Transportation', 400, '', ''],
        ['Insurance', 200, '', ''],
        ['Entertainment', 300, '', ''],
        ['Savings', 1000, '', ''],
        ['Other Expenses', 200, '', ''],
        ['Total Expenses', 4500, '', ''],
        ['', '', '', ''],
        ['Net Income', 2000, '', ''],
      ],
      formulas: { 'B7': '=SUM(B4:B6)', 'B18': '=SUM(B10:B17)', 'B20': '=B7-B18' },
      active: true,
      filter: true,
    },
  ],
  showFormulaBar: true,
  showSheetTab: true,
  dragOrder: {
    enableDragColumnOrder: true,
    enableDragRowOrder: true,
  },
  undoRedo: { show: true },
  defaultRowHeight: 25,
  defaultColWidth: 120,
}

export const OKR_TEMPLATE_DATA: IVTableSheetOptions = {
  sheets: [
    {
      sheetKey: 'okr-sheet',
      sheetTitle: 'OKRs',
      columnCount: 6,
      rowCount: 100,
      data: [
        ['Objective', 'Key Result', 'Owner', 'Target', 'Current', 'Confidence'],
        ['Increase product adoption', 'Weekly active users to 15k', 'Growth', 15000, 9200, 'Medium'],
        ['', 'Activation rate to 45%', 'Product', 0.45, 0.32, 'Medium'],
        ['Delight customers', 'CSAT 4.6+', 'Support', 4.6, 4.4, 'High'],
      ],
      active: true,
      filter: true,
    },
  ],
  showFormulaBar: true,
  showSheetTab: true,
  dragOrder: {
    enableDragColumnOrder: true,
    enableDragRowOrder: true,
  },
  undoRedo: { show: true },
  defaultRowHeight: 25,
  defaultColWidth: 100,
}

export const TASKS_TEMPLATE_DATA: IVTableSheetOptions = {
  sheets: [
    {
      sheetKey: 'tasks-sheet',
      sheetTitle: 'Tasks',
      columnCount: 5,
      rowCount: 100,
      data: [
        ['Task', 'Assignee', 'Status', 'Due', 'Notes'],
        ['Scope homepage revamp', 'Alex', 'In Progress', new Date(Date.now() + 5 * 86400000).toLocaleDateString(), 'Finalize IA'],
        ['Migrate billing webhooks', 'Sam', 'To Do', new Date(Date.now() + 10 * 86400000).toLocaleDateString(), ''],
        ['Publish Q1 roadmap', 'Taylor', 'Done', new Date().toLocaleDateString(), 'Share with GTM'],
      ],
      active: true,
      filter: true,
    },
  ],
  showFormulaBar: true,
  showSheetTab: true,
  dragOrder: {
    enableDragColumnOrder: true,
    enableDragRowOrder: true,
  },
  undoRedo: { show: true },
  defaultRowHeight: 25,
  defaultColWidth: 120,
}

export const EXPENSE_TRACKER_TEMPLATE_DATA: IVTableSheetOptions = {
  sheets: [
    {
      sheetKey: 'expenses-sheet',
      sheetTitle: 'Expenses',
      columnCount: 4,
      rowCount: 100,
      data: [
        ['Expense Tracker', '', '', ''],
        ['', '', '', ''],
        ['Date', 'Description', 'Category', 'Amount'],
        [new Date().toLocaleDateString(), 'Coffee shop', 'Food & Dining', 5.50],
        [new Date(Date.now() - 86400000).toLocaleDateString(), 'Gas station', 'Transportation', 45.00],
        [new Date(Date.now() - 86400000).toLocaleDateString(), 'Grocery store', 'Food & Dining', 125.30],
        [new Date(Date.now() - 2 * 86400000).toLocaleDateString(), 'Streaming service', 'Entertainment', 14.99],
        [new Date(Date.now() - 3 * 86400000).toLocaleDateString(), 'Pharmacy', 'Healthcare', 28.75],
        ['', '', '', ''],
        ['Total Expenses', '', '', 219.54],
        ['', '', '', ''],
        ['Summary by Category', '', '', ''],
        ['Food & Dining', 130.80, '', ''],
        ['Transportation', 45.00, '', ''],
        ['Entertainment', 14.99, '', ''],
        ['Healthcare', 28.75, '', ''],
      ],
      active: true,
      filter: true,
    },
  ],
  showFormulaBar: true,
  showSheetTab: true,
  dragOrder: {
    enableDragColumnOrder: true,
    enableDragRowOrder: true,
  },
  undoRedo: { show: true },
  defaultRowHeight: 25,
  defaultColWidth: 120,
}

export const PROJECT_TIMELINE_TEMPLATE_DATA: IVTableSheetOptions = {
  sheets: [
    {
      sheetKey: 'timeline-sheet',
      sheetTitle: 'Timeline',
      columnCount: 6,
      rowCount: 100,
      data: [
        ['Project Timeline', '', '', '', '', ''],
        [],
        ['Phase', 'Task/Milestone', 'Owner', 'Start Date', 'End Date', 'Status'],
        ['Phase 1: Planning', 'Project kickoff', 'Project Manager', new Date().toLocaleDateString(), new Date().toLocaleDateString(), 'Completed'],
        ['', 'Requirements gathering', 'Business Analyst', new Date(Date.now() + 86400000).toLocaleDateString(), new Date(Date.now() + 5 * 86400000).toLocaleDateString(), 'In Progress'],
        ['', 'Technical design', 'Lead Developer', new Date(Date.now() + 3 * 86400000).toLocaleDateString(), new Date(Date.now() + 7 * 86400000).toLocaleDateString(), 'Not Started'],
        ['Phase 2: Development', 'Sprint planning', 'Scrum Master', new Date(Date.now() + 8 * 86400000).toLocaleDateString(), new Date(Date.now() + 8 * 86400000).toLocaleDateString(), 'Not Started'],
        ['', 'Core features development', 'Development Team', new Date(Date.now() + 9 * 86400000).toLocaleDateString(), new Date(Date.now() + 23 * 86400000).toLocaleDateString(), 'Not Started'],
        ['', 'Code review', 'Senior Developer', new Date(Date.now() + 20 * 86400000).toLocaleDateString(), new Date(Date.now() + 25 * 86400000).toLocaleDateString(), 'Not Started'],
        ['Phase 3: Testing', 'Testing kickoff', 'QA Lead', new Date(Date.now() + 24 * 86400000).toLocaleDateString(), new Date(Date.now() + 24 * 86400000).toLocaleDateString(), 'Not Started'],
        ['', 'Integration testing', 'QA Team', new Date(Date.now() + 25 * 86400000).toLocaleDateString(), new Date(Date.now() + 30 * 86400000).toLocaleDateString(), 'Not Started'],
        ['Phase 4: Deployment', 'Production release', 'DevOps Team', new Date(Date.now() + 31 * 86400000).toLocaleDateString(), new Date(Date.now() + 31 * 86400000).toLocaleDateString(), 'Not Started'],
        [],
        ['Summary', '', '', '', '', ''],
        ['Total Duration', '31 days', '', '', '', ''],
        ['Team Size', '8 people', '', '', '', ''],
      ],
      active: true,
      filter: true,
    },
  ],
  showFormulaBar: true,
  showSheetTab: true,
  dragOrder: {
    enableDragColumnOrder: true,
    enableDragRowOrder: true,
  },
  undoRedo: { show: true },
  defaultRowHeight: 25,
  defaultColWidth: 120,
}

export const SALES_CRM_TEMPLATE_DATA: IVTableSheetOptions = {
  sheets: [
    {
      sheetKey: 'crm-sheet',
      sheetTitle: 'Sales Pipeline',
      columnCount: 8,
      rowCount: 100,
      data: [
        ['Sales Pipeline', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['Deal Name', 'Company', 'Contact', 'Stage', 'Amount', 'Probability', 'Expected Close', 'Status'],
        ['Enterprise Software Deal', 'Tech Corp Inc', 'John Smith', 'Proposal', 125000, 0.75, new Date(Date.now() + 14 * 86400000).toLocaleDateString(), 'Hot'],
        ['Marketing Automation', 'Global Marketing Ltd', 'Sarah Johnson', 'Negotiation', 45000, 0.90, new Date(Date.now() + 7 * 86400000).toLocaleDateString(), 'Hot'],
        ['Cloud Migration', 'Data Systems Co', 'Mike Chen', 'Discovery', 280000, 0.25, new Date(Date.now() + 45 * 86400000).toLocaleDateString(), 'Warm'],
        ['Mobile App Development', 'StartupXYZ', 'Emily Davis', 'Qualification', 75000, 0.15, new Date(Date.now() + 60 * 86400000).toLocaleDateString(), 'Cold'],
        ['AI Integration Project', 'Innovation Labs', 'Robert Wilson', 'Demo Scheduled', 150000, 0.40, new Date(Date.now() + 21 * 86400000).toLocaleDateString(), 'Warm'],
        ['Security Audit Service', 'Finance Corp', 'Lisa Anderson', 'Initial Contact', 35000, 0.10, new Date(Date.now() + 90 * 86400000).toLocaleDateString(), 'Cold'],
        ['', '', '', '', '', '', '', ''],
        ['Pipeline Summary', '', '', '', '', '', '', ''],
        ['Total Pipeline Value', '$710,000', '', '', '', '', '', ''],
        ['Weighted Pipeline', '$356,500', '', '', '', '', '', ''],
        ['Hot Deals (2)', '$170,000', '', '', '', '', '', ''],
        ['Warm Deals (2)', '$355,000', '', '', '', '', '', ''],
        ['Cold Deals (2)', '$110,000', '', '', '', '', '', ''],
      ],
      active: true,
      filter: true,
    },
  ],
  showFormulaBar: true,
  showSheetTab: true,
  dragOrder: {
    enableDragColumnOrder: true,
    enableDragRowOrder: true,
  },
  undoRedo: { show: true },
  defaultRowHeight: 25,
  defaultColWidth: 120,
}

export const INVENTORY_TRACKER_TEMPLATE_DATA: IVTableSheetOptions = {
  sheets: [
    {
      sheetKey: 'inventory-sheet',
      sheetTitle: 'Inventory',
      columnCount: 8,
      rowCount: 100,
      data: [
        ['Inventory Tracker', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['SKU', 'Product Name', 'Category', 'Current Stock', 'Reorder Level', 'Unit Price', 'Total Value', 'Status'],
        ['LAP-001', 'Laptop Pro 15"', 'Electronics', 8, 10, 1299.99, 10399.92, 'Reorder Soon'],
        ['MOU-002', 'Wireless Mouse', 'Accessories', 45, 20, 29.99, 1349.55, 'Good Stock'],
        ['KEY-003', 'Mechanical Keyboard', 'Accessories', 12, 15, 89.99, 1079.88, 'Reorder Soon'],
        ['MON-004', '4K Monitor 27"', 'Electronics', 3, 8, 399.99, 1199.97, 'Low Stock'],
        ['CHA-005', 'USB-C Cable 2m', 'Accessories', 120, 50, 12.99, 1558.80, 'Good Stock'],
        ['DES-006', 'Standing Desk', 'Furniture', 6, 5, 499.99, 2999.94, 'Low Stock'],
        ['PRI-007', 'Inkjet Printer', 'Office', 18, 10, 149.99, 2699.82, 'Good Stock'],
        ['PAP-008', 'A4 Paper (500 sheets)', 'Office', 85, 30, 8.99, 764.15, 'Good Stock'],
        ['TAB-009', 'Tablet 10"', 'Electronics', 4, 6, 249.99, 999.96, 'Low Stock'],
        ['', '', '', '', '', '', '', ''],
        ['Inventory Summary', '', '', '', '', '', '', ''],
        ['Total Products', 9, '', '', '', '', '', ''],
        ['Total Items in Stock', 311, '', '', '', '', '', ''],
        ['Total Inventory Value', 23352.99, '', '', '', '', '', ''],
        ['Low Stock Items', 3, '', '', '', '', '', ''],
      ],
      active: true,
      filter: true,
    },
  ],
  showFormulaBar: true,
  showSheetTab: true,
  dragOrder: {
    enableDragColumnOrder: true,
    enableDragRowOrder: true,
  },
  undoRedo: { show: true },
  defaultRowHeight: 25,
  defaultColWidth: 120,
}

export const CONTENT_CALENDAR_TEMPLATE_DATA: IVTableSheetOptions = {
  sheets: [
    {
      sheetKey: 'calendar-sheet',
      sheetTitle: 'Content Calendar',
      columnCount: 8,
      rowCount: 100,
      data: [
        ['Content Calendar', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['Publish Date', 'Content Title', 'Channel', 'Content Type', 'Author', 'Status', 'Target Audience', 'Notes'],
        [new Date().toLocaleDateString(), '10 Tips for Remote Work Success', 'Blog', 'Article', 'Sarah Chen', 'Published', 'Remote workers', 'SEO optimized'],
        [new Date(Date.now() + 86400000).toLocaleDateString(), 'Product Walkthrough', 'YouTube', 'Video', 'Mike Johnson', 'Scheduled', 'Prospects', '3-minute overview'],
        [new Date(Date.now() + 2 * 86400000).toLocaleDateString(), 'Industry Trends Report', 'LinkedIn', 'Infographic', 'Emily Davis', 'In Progress', 'B2B professionals', 'Q3 data analysis'],
        [new Date(Date.now() + 3 * 86400000).toLocaleDateString(), 'Customer Success Story', 'Blog', 'Case Study', 'Alex Rivera', 'Idea', 'Enterprise prospects', 'Interview scheduled'],
        [new Date(Date.now() + 4 * 86400000).toLocaleDateString(), 'Weekly Tech Tips', 'Twitter', 'Thread', 'Chris Lee', 'Scheduled', 'Developers', 'Part 4 of series'],
        [new Date(Date.now() + 5 * 86400000).toLocaleDateString(), 'Product Launch Announcement', 'Email Newsletter', 'Newsletter', 'Marketing Team', 'In Progress', 'All subscribers', 'Major launch'],
        [new Date(Date.now() + 7 * 86400000).toLocaleDateString(), 'How-to Guide: Getting Started', 'Blog', 'Tutorial', 'Jamie Wilson', 'Idea', 'New users', 'Include visual steps'],
        [new Date(Date.now() + 10 * 86400000).toLocaleDateString(), 'Behind the Scenes: Team Culture', 'Instagram', 'Reels', 'Social Media Team', 'Idea', 'General audience', 'Team photos needed'],
        [new Date(Date.now() + 14 * 86400000).toLocaleDateString(), 'Q3 Results Webinar', 'Webinar', 'Webinar', 'CEO + Sales Team', 'Scheduled', 'Investors & Partners', 'Registration open'],
        ['', '', '', '', '', '', '', ''],
        ['Content Summary', '', '', '', '', '', '', ''],
        ['Total Content Pieces', 9, '', '', '', '', '', ''],
        ['Published', 1, '', '', '', '', '', ''],
        ['Scheduled', 3, '', '', '', '', '', ''],
        ['In Progress', 2, '', '', '', '', '', ''],
        ['Ideas', 3, '', '', '', '', '', ''],
      ],
      active: true,
      filter: true,
    },
  ],
  showFormulaBar: true,
  showSheetTab: true,
  dragOrder: {
    enableDragColumnOrder: true,
    enableDragRowOrder: true,
  },
  undoRedo: { show: true },
  defaultRowHeight: 25,
  defaultColWidth: 140,
}

export const INVOICE_TEMPLATE_DATA: IVTableSheetOptions = {
  sheets: [
    {
      sheetKey: 'invoice-sheet',
      sheetTitle: 'Invoice',
      columnCount: 5,
      rowCount: 100,
      data: [
        ['Your Company Name', '', '', '', 'INVOICE'],
        ['123 Business Street', '', '', '', 'Invoice #: INV-001'],
        ['City, State 12345', '', '', '', 'Date: ' + new Date().toLocaleDateString()],
        ['Phone: (555) 123-4567', '', '', '', 'Due Date: ' + new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString()],
        ['', '', '', '', ''],
        ['Bill To:', '', '', '', ''],
        ['Client Name', '', '', '', ''],
        ['Client Address', '', '', '', ''],
        ['City, State ZIP', '', '', '', ''],
        ['', '', '', '', ''],
        ['Description', 'Quantity', 'Rate', 'Amount', ''],
        ['Web Development Services', 40, 75, 3000, ''],
        ['Design Consultation', 10, 100, 1000, ''],
        ['Project Management', 20, 50, 1000, ''],
        ['', '', '', '', ''],
        ['', '', 'Subtotal:', 5000, ''],
        ['', '', 'Tax (8.5%):', 425, ''],
        ['', '', 'Total:', 5425, ''],
        ['', '', '', '', ''],
        ['Notes:', '', '', '', ''],
        ['Payment is due within 30 days of invoice date.', '', '', '', ''],
        ['Thank you for your business!', '', '', '', ''],
      ],
      formulas: {
        'D12': '=B12*C12',
        'D13': '=B13*C13',
        'D14': '=B14*C14',
        'D16': '=SUM(D12:D14)',
        'D17': '=D16*0.085',
        'D18': '=D16+D17',
      },
      active: true,
      filter: true,
    },
  ],
  showFormulaBar: true,
  showSheetTab: true,
  dragOrder: {
    enableDragColumnOrder: true,
    enableDragRowOrder: true,
  },
  undoRedo: { show: true },
  defaultRowHeight: 25,
  defaultColWidth: 140,
}
